name: chrome
homepage: https://github.com/dart-gde/chrome.dart
version: 0.0.1
author: Adam Singer <financeCoding@gmail.com>
dependencies:
  hop: any
  js: any
  unittest: any
  logging: any
  browser: any
